Users/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import *

app_name="Users"

urlpatterns = [
    url(r'^update_user/',update_user,name="update_user"),
    url(r'^password/',change_password,name="update_password"),
    url(r'^signup/', Signup.as_view(),name="SignUp"),
    url(r'^Signin/',SignIn,name='SignIn'),
    url(r'^Logout/',SignOut,name='SignOut'),
    url(r'^admin/', admin.site.urls),
]

api/urls.py
from django.conf.urls import url,include

from .views import *


urlpatterns = [
    url(r'tutorial/postings/(?P<pk>[-\w]+)/$',Tutorial_Post_RUD_view.as_view(),name='post-tut-rud'),
    url(r'tutorial/create/$',Tutorial_Post_List_Create_view.as_view(),name='post-tut-create'),
    url(r'article/postings/(?P<pk>[-\w]+)/$',Article_Post_RUD_view.as_view(),name='post-art-rud'),
    url(r'article/create/$',Article_Post_List_Create_view.as_view(),name='post-art-create'),
    url(r'tutorial/posts/',Tutorial_Get_All_Posts.as_view(),name='post-tut-all'),
    url(r'article/posts/',Article_Get_All_Posts.as_view(),name='post-article-all'),
]

blog_content/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *
from django.conf.urls.static import static
from django.conf import settings


app_name="blog_content"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home$',home.as_view(),name="home"),
    url(r'list_linux$',List_Linux.as_view(),name="list_linux"),
    url(r'list_python$',List_Python.as_view(),name="list_python"),
    url(r'list_bash$',List_Bash.as_view(),name="list_bash"),
    url(r'list_perl$',List_Perl.as_view(),name="list_perl"),
    url(r'list_news$',List_News.as_view(),name="list_news"),
    url(r'^tut_detail/(?P<pk>[-\w]+)/$',Tut_Detail.as_view(),name="tut_detail"),
    url(r'^news_detail/(?P<pk>[-\w]+)/$',News_Detail.as_view(),name="news_detail"),
    url(r'^news_detail/',add_news_like,name="like_article"),
    url(r'^tut_detail/',add_tut_like,name="like_tutorial"),
    url(r'^tut_comment/',Tut_Comment_Update,name="tut_comment"),
    url(r'^news_comment/',News_Comment_Update,name="news_comment"),
    url(r'^add_tutorial/',add_tutorial.as_view(),name="add_tutorial"),
    url(r'^modify_tut/(?P<pk>[-\w]+)/$',Update_Tut.as_view(),name="update_tut"),
    url(r'^modify_news/(?P<pk>[-\w]+)/$',Update_News.as_view(),name="update_news"),
    url(r'^list_my_aricles/',List_User_Articles,name="list_my_articles"),
    url(r'^add_article/',add_article.as_view(),name="add_article"),
    url(r'^search/',search_item,name='search'),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tech_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog_content.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'$^',List_News.as_view(),name="home"),
    url(r'^blog_content/',include("blog_content.urls")),
    url(r'^Users/',include("Users.urls")),
    url(r'^api/',include('api.urls')),



]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog_content/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class Topic(models.Model):
    tech_type = models.CharField(max_length=256,unique=True)

    def __str__(self):
        return self.tech_type

class Tutorial(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    Title = models.CharField(unique=True,max_length=256,default="")
    category = models.ForeignKey(Topic,on_delete=models.CASCADE)
    date_created = models.DateField(default=timezone.now)
    date_modified = models.DateField(null=True,blank=True)
    description = models.TextField()
    Content = models.TextField()
    search_criteria = models.TextField()
    content_html = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('blog_content:list_news')

    def __str__(self):
        return self.Title


class TutLikeCount(models.Model):
    tut = models.OneToOneField(Tutorial,unique=True,on_delete=models.CASCADE)
    users = models.TextField(default="[]")


    def __str__(self):
        return str(self.tut)


class TutorialComment(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    Tutorial = models.ForeignKey(Tutorial,on_delete=models.CASCADE)
    comment = models.TextField()
    date_commented = models.DateField(default=timezone.now())

    def __str__(self):
        return self.comment






class NewsArticle(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    Title = models.CharField(unique=True,max_length=256,default="")
    date_created = models.DateField(default=timezone.now)
    description = models.TextField()
    Content = models.TextField()
    search_criteria = models.TextField()
    content_html = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('blog_content:list_news')

    def __str__(self):
        return self.Title


class NewsLikeCount(models.Model):
    news = models.OneToOneField(NewsArticle,unique=True,on_delete=models.CASCADE)
    users = models.TextField(default="[]")


    def __str__(self):
        return str(self.news)



class NewsComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    news_article = models.ForeignKey(NewsArticle)
    comment = models.TextField()
    date_commented = models.DateField(default=timezone.now())

blog_content/forms.py
from django.forms import ModelForm
from .models import *


class News_Form(ModelForm):

    class Meta:
        model = NewsArticle
        fields = ['Title','description','Content','search_criteria','content_html']


class Tutorial_Form(ModelForm):

    class Meta:
        model = Tutorial
        fields = ['Title','category','description','Content','search_criteria','content_html']

blog_content/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView,TemplateView,DetailView,CreateView,UpdateView
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from .models import *
from django.shortcuts import render
from django.http import JsonResponse
from .forms import *
import unicodedata



# Create your views here.

class home(TemplateView):
    template_name = "blog_content/home.html"


class List_Python(ListView):
    model = Tutorial
    template_name = "blog_content/List_Python.html"

    def get_queryset(self):
        topic_val = Topic.objects.get(tech_type='Python')
        queryset = Tutorial.objects.filter(category=topic_val.id)
        return queryset



class List_Linux(ListView):
    model = Tutorial
    template_name = "blog_content/List_Linux.html"

    def get_queryset(self):
        topic_val = Topic.objects.get(tech_type='Linux')
        queryset = Tutorial.objects.filter(category=topic_val.id)
        return queryset

class List_Bash(ListView):
    model = Tutorial
    template_name = "blog_content/List_Bash.html"

    def get_queryset(self):
        topic_val = Topic.objects.get(tech_type='Bash')
        queryset = Tutorial.objects.filter(category=topic_val.id)
        return queryset


class List_Perl(ListView):
    model = Tutorial
    template_name = "blog_content/List_Perl.html"

    def get_queryset(self):
        topic_val = Topic.objects.get(tech_type='Perl')
        queryset = Tutorial.objects.filter(category=topic_val.id)
        return queryset

class List_News(ListView):
    model = NewsArticle
    template_name = "blog_content/List_Articles.html"

class News_Detail(DetailView):
    model = NewsArticle
    template_name = "blog_content/News_Detail.html"

    def get_context_data(self,**kwargs):

        context = super(News_Detail,self).get_context_data(**kwargs)
        context['comments'] = NewsComment.objects.filter(news_article = kwargs['object'])
        try:
            like_list = str(NewsLikeCount.objects.get(news=kwargs['object']).users).split(',')
            del like_list[len(like_list)-1]
        except:
            like_list = []

        context['likes'] = len(like_list)



        if self.request.user.username in like_list:
            context['already_liked'] = True
            print("User is in like list")

        else:
            context['alread_liked'] = False
            print("User is not in like list")

        return context

def News_Comment_Update(request):

    if request.method=="POST" and request.is_ajax():
        try:
            user_ob = request.user
            title = request.POST['title']
            title_ob = NewsArticle.objects.get(Title=title)
            this_comment = request.POST['comment']
            write = NewsComment(author=user_ob,news_article=title_ob,comment=this_comment)
            write.save()
            print("saved!")
            return JsonResponse({'status':'Success','msg':'saved comment successfully'})
        except TutorialComment.DoesNotExist:
            return JsonResponse({'status':'Fail', 'msg': 'Object does not exist'})

    else:
        return JsonResponse({'status': 'Fail', 'msg': 'Not a valid request'})





class Tut_Detail(DetailView):
    model = Tutorial
    template_name = "blog_content/Tut_Detail.html"

    def get_context_data(self,**kwargs):

        context = super(Tut_Detail,self).get_context_data(**kwargs)
        context['comments'] = TutorialComment.objects.filter(Tutorial = kwargs['object'])
        try:
            like_list = str(TutLikeCount.objects.get(tut=kwargs['object']).users).split(',')
            del like_list[len(like_list)-1]

        except Exception as e:

            print (e)
            like_list = []

        print(len(like_list))
        context['likes'] = len(like_list)



        if self.request.user.username in like_list:
            context['already_liked'] = True
            print("User is in like list")

        else:
            context['alread_liked'] = False
            print("User is not in like list")

        return context


def Tut_Comment_Update(request):

    if request.method=="POST" and request.is_ajax():
        try:
            user_ob = request.user
            title = request.POST['title']
            title_ob = Tutorial.objects.get(Title=title)
            this_comment = request.POST['comment']
            write = TutorialComment(author=user_ob,Tutorial=title_ob,comment=this_comment)
            write.save()
            print("saved!")
            return JsonResponse({'status':'Success','msg':'saved comment successfully'})
        except TutorialComment.DoesNotExist:
            return JsonResponse({'status':'Fail', 'msg': 'Object does not exist'})

    else:
        return JsonResponse({'status': 'Fail', 'msg': 'Not a valid request'})


class add_tutorial(CreateView):
    model = Tutorial
    fields = ['Title', 'category', 'description', 'Content', 'search_criteria', 'content_html']
    template_name = "blog_content/add_tutorial.html"

    def form_valid(self,form):
        user = self.request.user
        form.instance.author = user

        return super(add_tutorial,self).form_valid(form)


class add_article(CreateView):
    model = NewsArticle
    fields = ['Title', 'description', 'Content', 'search_criteria', 'content_html']
    template_name = "blog_content/add_article.html"


    def form_valid(self,form):
        user = self.request.user
        form.instance.author = user

        return super(add_article,self).form_valid(form)



def add_news_like(request):

    if request.method == "POST" and request.is_ajax():

        try:
            title = request.POST['title']
            user = request.user
            news_obj = NewsArticle.objects.get(Title=title)

            if not NewsLikeCount.objects.filter(news=news_obj).exists():

                news_like_obj = NewsLikeCount(news = news_obj,users = str(request.user)+",")

            else:

                news_like_obj = NewsLikeCount.objects.get(news=news_obj)

                user_list = str(news_like_obj.users)
                if request.user.username not in user_list:
                    user_list+=str(request.user)+","
                    news_like_obj.users = str(user_list)

            news_like_obj.save()

            return JsonResponse({'status': 'Success', 'msg': 'like saved successfully'})

        except NewsArticle.DoesNotExist:

            return JsonResponse({'status': 'Fail', 'msg': 'Object does not exist'})

    else:
        return JsonResponse({'status': 'Fail', 'msg': 'Not a valid request'})




def add_tut_like(request):
    if request.method == "POST" and request.is_ajax():

        try:
            title = request.POST['title']

            tut_obj = Tutorial.objects.get(Title=title)
            if not TutLikeCount.objects.filter(tut=tut_obj).exists():
                tut_like_obj = TutLikeCount(tut=tut_obj, users= str(request.user) + ",")
            else:
                tut_like_obj = TutLikeCount.objects.get(tut=tut_obj)
                user_list = str(tut_like_obj.users)
                if request.user.username not in user_list:
                    user_list += str(request.user) + ","
                    tut_like_obj.users = str(user_list)

            tut_like_obj.save()

            return JsonResponse({'status': 'Success', 'msg': 'like saved successfully'})

        except Tutorial.DoesNotExist:

            return JsonResponse({'status': 'Fail', 'msg': 'Object does not exist'})

    else:
        return JsonResponse({'status': 'Fail', 'msg': 'Not a valid request'})



def search_item(request):
    if request.method=="POST":
        news_criteria = {}
        tut_criteria = {}
        news_articles = NewsArticle.objects.all()
        tuts = Tutorial.objects.all()
        for article in news_articles:
            data = article.search_criteria.lower()
            if ',' in data:
                delimitied_data = data.split(',')
                news_criteria[article.Title] = delimitied_data
            else:
                news_criteria[article.Title] = data

        for tut in tuts:
            tut_data = tut.search_criteria.lower()
            if ',' in tut_data:
                tut_delimitied_data = tut_data.split(',')
                tut_criteria[tut.Title] = tut_delimitied_data
            else:
                tut_criteria[tut.Title] = tut_data

        print(news_criteria)
        print(tut_criteria)

        form_data = request.POST.get('search_criteria').lower()
        matching_news_items = []
        matching_tut_items = []

        for entry in news_criteria:

            if isinstance(news_criteria[entry],list):
                for item in news_criteria[entry]:
                    if form_data in item:
                        matching_news_items.append(NewsArticle.objects.get(Title=entry))
                        break


            else:
                if form_data in news_criteria[entry]:
                    matching_news_items.append(NewsArticle.objects.get(Title=entry))


        for entry in tut_criteria:

            if isinstance(tut_criteria[entry],list):
                for item in tut_criteria[entry]:
                    if form_data in item:
                        matching_tut_items.append(Tutorial.objects.get(Title=entry))
                        break


            else:
                if form_data in tut_criteria[entry]:
                    matching_tut_items.append(Tutorial.objects.get(Title=entry))

        return render(request,"blog_content/results.html",{"news":matching_news_items,"tuts":matching_tut_items})
    return render(request,"blog_content/results.html")



class Update_News(UpdateView):
    model = NewsArticle
    fields = ['Title', 'description', 'Content', 'search_criteria', 'content_html']
    template_name = "blog_content/update_news.html"

class Update_Tut(UpdateView):

blog_content/templates/blog_content/List_Articles.html
{% extends 'blog_content/base.html' %}
{% load static %}

{% block Title_Block %}Latest News{% endblock %}

{% block Body_Block %}
    <div style="float:center;position:fixed"><img style="width:50%;height:auto;" src="/media/images/news.jpg"></div>
    <h3 style="text-align:center">Lastest News:</h3>
    {% for article in object_list %}
        <div class="col-sm-6 col-sm-offset-3 jumbotron list_tuts">
        <h2><a href="{% url 'blog_content:news_detail' pk=article.pk %}">{{article.Title}}</a></h2><br>

        <h3>{{article.description}}</h3><br>
        <p>Date Published: {{article.date_created}}</p>
        <p>Author: {{article.author}}</p>
        </div>
    {% endfor %}

{% endblock %}

blog_content/templates/blog_content/List_Bash.html
{% extends 'blog_content/base.html' %}


{% block Title_Block %}Bash Tuts{% endblock %}

{% block Body_Block %}
    <div style="float:left;position:fixed"><img style="width:38%;height:auto;" src="/media/images/bash.png"></div>

    {% for article in object_list %}
        <div class="col-sm-6 col-sm-offset-3 jumbotron list_tuts">
        <h2><a href="{% url 'blog_content:tut_detail' pk=article.pk %}">{{article.Title}}</a></h2><br>

        <h3>{{article.description}}</h3><br>
        <p>Date Published: {{article.date_created}}</p>
        <p>Author: {{article.author}}</p>
        </div>
    {% endfor %}

{% endblock %}

blog_content/templates/blog_content/News_Detail.html
{% extends 'blog_content/base.html' %}
{% load static %}

{% block Title_Block %}News Article{% endblock %}

{% block Body_Block %}
    <div class="col-xs-10 col-xs-offset-1 jumbotron">
        <div class="img_center"><h1>{{ newsarticle.Title }}</h1></div><br>
        <div style="text-align:center">
            Date published: {{ newsarticle.date_created }}<br>
            Author: {{ newsarticle.author }}<br>
        </div>

        <div class="img_center"><h2>{{ newsarticle.description }}</h2></div>
        {{ newsarticle.Content|safe }}<br>

        <div>
        {% if user.is_authenticated %}
            {% if already_liked %}
                <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true" style="color:grey" ></span><br>
            {% else %}
                <a id="like" href="javascript:void(0)"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></a><br>
            {% endif %}
        {% else %}
            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true" style="color:red" ></span>&nbsp;&nbsp;Please Signin to like<br>
        {% endif %}

        Likes: {{likes}}

        </div>


        <br><br>
        <h3>Comments:</h3><hr>
        {% for comment in comments %}
            {% if comment.author.is_superuser %}

                 <div style=" border-radius:5px; background-color:#ffffcc; width:40%;">
                 <p>{{comment.author}}(Admin):&nbsp;&nbsp;&nbsp;&nbsp;{{comment.comment}}</p>
                 <small>{{comment.date_commented}}</small>
                 </div><br>

            {% else %}

                 <div style=" border-radius:5px; background-color:#ffffcc; width:40%;">
                 <p>{{comment.author}}: {{comment.comment}}</p>
                 <small>{{comment.date_commented}}</small>
                 </div><br>

            {% endif %}


        {% endfor %}

        {% if user.is_authenticated %}
        <br><hr>

        <label for="comment">Comment:</label><br>
        <textarea id="comment" cols="50" rows="2" placeholder="Please enter Comment here"></textarea><br>
        <input type="submit" id="submit_comment" value="Submit">

        <script>

        $(document).ready(function(){
              $("#submit_comment").click(function(){
            $.ajax({ type: "POST",
                    url:"{% url 'blog_content:news_comment' %}",
                    data: { "title": "{{newsarticle}}","comment":$("#comment").val(),csrfmiddlewaretoken:'{{csrf_token}}' },
                    success:function(msg){
                    location.reload(true);
                    console.log("Saved Comment");


                   }


                   });
                   });



              $("#like").click(function(){
            $.ajax({ type: "POST",
                    url:"{% url 'blog_content:like_article' %}",
                    data: { "title": "{{newsarticle}}",csrfmiddlewaretoken:'{{csrf_token}}' },
                    success:function(msg){
                    location.reload(true);
                    console.log("Added Like");


                   }});
                   });
             });





        </script>
        {% else %}

        <p>Please Sign in to Comment :)</p>

        {% endif %}

    </div>

{% endblock %}

blog_content/templates/blog_content/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
      <meta charset="UTF-8">
      <title>{% block Title_Block %}{% endblock %}</title>
      <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
      <!--<script src="{% static 'js/jQuery_3.3.1.js' %}"></script>-->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/master.css' %}">


  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'blog_content:list_news' %}">Tech Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tutorials <span class="caret"></span></a>
              <ul class="dropdown-menu  ">
                <li><a href="{% url 'blog_content:list_linux' %}">Linux</a></li>
                <li><a href="{% url 'blog_content:list_bash' %}">Bash</a></li>
                <li><a href="{% url 'blog_content:list_python' %}">Python</a></li>
                <li><a href="{% url 'blog_content:list_perl' %}">Perl</a></li>
              </ul>
            </li>

            <li><a href="{% url 'blog_content:home' %}">About Us</a></li>
          </ul>

          <form class="navbar-form navbar-left" action="{% url 'blog_content:search' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <input id="search_criteria" name="search_criteria" type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default" id="search">Search</button>
          </form>


             <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
                 <li><a href="{% url 'Users:SignIn' %}">Sign In</a></li>
                 <li><a href="{% url 'Users:SignUp' %}">Sign Up</a></li>
            {% else %}

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.username}} <span class="caret"></span></a>
              <ul class="dropdown-menu inverse-dropdown">
                <li><a href="{% url 'Users:update_user'%}">Modify Account</a></li>
                  <li><a href="{% url 'Users:update_password'%}">Change Password</a></li>
                  <li><a href="{% url 'blog_content:add_tutorial' %}">Create Tutorial</a></li>
                  <li><a href="{% url 'blog_content:add_article' %}">Create News Article</a></li>
                  <li><a href="{% url 'blog_content:list_my_articles' %}">Modify My Articles</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'Users:SignOut' %}">Logout</a></li>
              </ul>
            </li>
            {% endif %}
             </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


  {% block Body_Block %}
  {% endblock %}






  </body>
</html>

blog_content/templates/blog_content/home.html
{% extends 'blog_content/base.html' %}
{% load static %}

{% block Title_Block %}Home{% endblock %}
{% load static %}
{% block Body_Block %}

<div class="col-md-6 col-md-offset-3">
    <h1 class="main_h1">
        Welcome
    </h1><br><br>
    <div class="main_h1"><img  src="/media/images/pengy.png"></div><br>
    <h3 class="main_h1">
        This is a Blog sites with the latest Linux and Scripting news and tutorials available for the avid admin
    </h3><br><br><br>


    <div class="img_center">
        <div class="img_container ">
            <a href="{% url 'blog_content:list_linux' %}"><img class="image_link" src="/media/images/linux.png"></a>
            <a href="{% url 'blog_content:list_bash' %}"><img class="image_link"  src="/media/images/bash.png"></a>
            <a href="{% url 'blog_content:list_python' %}"><img class="image_link"  src="/media/images/python.png"></a>
            <a href="{% url 'blog_content:list_perl' %}"><img class="image_link"  src="/media/images/perl.png"></a>
        </div>
    </div>


</div>
{% endblock %}

blog_content/templates/blog_content/results.html
{% extends 'blog_content/base.html' %}


{% block Title_Block %}Search Results:{% endblock %}

{% block Body_Block %}

    {% if news %}
    <div class="col-md-6 col-md-offset-3"><h2 style="text-align:center">News Results:</h2><hr></div>
    {% for article in news %}

        <div class="col-md-6 col-md-offset-3 jumbotron list_tuts">
        <h2><a href="{% url 'blog_content:news_detail' pk=article.pk %}">{{article.Title}}</a></h2><br>

        <h3>{{article.description}}</h3><br>
        <p>Date Published: {{article.date_created}}</p>
        <p>Author: {{article.author}}</p>
        </div>

    {% endfor %}
    {% endif %}

  </br></br>

    {% if tuts %}
    <div class="col-md-6 col-md-offset-3"><h2 style="text-align:center">Tutorial Results:</h2><hr></div>
    {% for article in tuts %}

        <div class="col-md-6 col-md-offset-3 jumbotron list_tuts">
        <h2><a href="{% url 'blog_content:tut_detail' pk=article.pk %}">{{article.Title}}</a></h2><br>

        <h3>{{article.description}}</h3><br>
        <p>Date Published: {{article.date_created}}</p>
        <p>Author: {{article.author}}</p>
        </div>

    {% endfor %}
    {% endif %}

    {% if not news and not tuts%}
        <br><br><h2 style="text-align:center">Sorry nothing found!</h2>
    {% endif %}

{% endblock %}
<!--<div style="float:left;position:fixed"></div><img style="width:50%;height:auto;" src="/media/images/linux.png">-->

blog_content/templates/blog_content/user_blogs.html
{% extends 'blog_content/base.html' %}


{% block Title_Block %}User Articles:{% endblock %}

{% block Body_Block %}


    <div class="col-md-6 col-md-offset-3"><h2 style="text-align:center">News Articles:</h2><hr></div>
    {% for article in news %}

        <div class="col-md-6 col-md-offset-3 jumbotron list_tuts">
        <h2><a href="{% url 'blog_content:update_news' pk=article.pk %}">{{article.Title}}</a></h2><br>

        <h3>{{article.description}}</h3><br>
        <p>Date Published: {{article.date_created}}</p>
        <p>Author: {{article.author}}</p>
        </div>

    {% endfor %}


  </br></br>


    <div class="col-md-6 col-md-offset-3"><h2 style="text-align:center">Tutorial Articles:</h2><hr></div>
    {% for article in tuts %}

        <div class="col-md-6 col-md-offset-3 jumbotron list_tuts">
        <h2><a href="{% url 'blog_content:update_tut' pk=article.pk %}">{{article.Title}}</a></h2><br>

        <h3>{{article.description}}</h3><br>
        <p>Date Published: {{article.date_created}}</p>
        <p>Author: {{article.author}}</p>
        </div>

    {% endfor %}



{% endblock %}
<!--<div style="float:left;position:fixed"></div><img style="width:50%;height:auto;" src="/media/images/linux.png">-->