Users/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import *

app_name="Users"

urlpatterns = [
    url(r'^update_user/',update_user,name="update_user"),
    url(r'^password/',change_password,name="update_password"),
    url(r'^signup/', Signup.as_view(),name="SignUp"),
    url(r'^Signin/',SignIn,name='SignIn'),
    url(r'^Logout/',SignOut,name='SignOut'),
    url(r'^admin/', admin.site.urls),
]

api/urls.py
from django.conf.urls import url,include

from .views import *


urlpatterns = [
    url(r'tutorial/postings/(?P<pk>[-\w]+)/$',Tutorial_Post_RUD_view.as_view(),name='post-tut-rud'),
    url(r'tutorial/create/$',Tutorial_Post_List_Create_view.as_view(),name='post-tut-create'),
    url(r'article/postings/(?P<pk>[-\w]+)/$',Article_Post_RUD_view.as_view(),name='post-art-rud'),
    url(r'article/create/$',Article_Post_List_Create_view.as_view(),name='post-art-create'),
    url(r'tutorial/posts/',Tutorial_Get_All_Posts.as_view(),name='post-tut-all'),
    url(r'article/posts/',Article_Get_All_Posts.as_view(),name='post-article-all'),
]

blog_content/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *
from django.conf.urls.static import static
from django.conf import settings


app_name="blog_content"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home$',home.as_view(),name="home"),
    url(r'list_linux$',List_Linux.as_view(),name="list_linux"),
    url(r'list_python$',List_Python.as_view(),name="list_python"),
    url(r'list_bash$',List_Bash.as_view(),name="list_bash"),
    url(r'list_perl$',List_Perl.as_view(),name="list_perl"),
    url(r'list_news$',List_News.as_view(),name="list_news"),
    url(r'^tut_detail/(?P<pk>[-\w]+)/$',Tut_Detail.as_view(),name="tut_detail"),
    url(r'^news_detail/(?P<pk>[-\w]+)/$',News_Detail.as_view(),name="news_detail"),
    url(r'^news_detail/',add_news_like,name="like_article"),
    url(r'^tut_detail/',add_tut_like,name="like_tutorial"),
    url(r'^tut_comment/',Tut_Comment_Update,name="tut_comment"),
    url(r'^news_comment/',News_Comment_Update,name="news_comment"),
    url(r'^add_tutorial/',add_tutorial.as_view(),name="add_tutorial"),
    url(r'^modify_tut/(?P<pk>[-\w]+)/$',Update_Tut.as_view(),name="update_tut"),
    url(r'^modify_news/(?P<pk>[-\w]+)/$',Update_News.as_view(),name="update_news"),
    url(r'^list_my_aricles/',List_User_Articles,name="list_my_articles"),
    url(r'^add_article/',add_article.as_view(),name="add_article"),
    url(r'^search/',search_item,name='search'),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tech_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog_content.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'$^',List_News.as_view(),name="home"),
    url(r'^blog_content/',include("blog_content.urls")),
    url(r'^Users/',include("Users.urls")),
    url(r'^api/',include('api.urls')),



]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Users/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse
from django.db import models



class UserMethods(User):
    def get_absolute_url(self):
        return reverse('Users:update_user', args=(self.id,))

Users/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

from django.db import models

# Create your models here.
class UserCreateForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ['username','email','password1','password2']

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            self.fields['username'].label = 'Display Name:'
            self.fields['email'].label = 'Email:'


class User_Update_Form(UserChangeForm):

    class Meta:
        model = User
        fields = ['first_name','last_name','email','password']










    '''def clean_password(self):

        if self.password != self.password2:
            raise forms.ValidationError("Passwords do NOT match!")'''

Users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
from django.views.generic import CreateView,UpdateView
from django.contrib.auth import (
    views as auth_views,
    logout,
    login,
    authenticate,
    get_user_model,
    update_session_auth_hash)
from .forms import User_Update_Form
from django.http import HttpResponseRedirect,HttpResponse
from .forms import *
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth.mixins import(LoginRequiredMixin,PermissionRequiredMixin)



# Create your views here.

class Signup(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('blog_content:home')
    template_name = "Users/signup.html"

def SignOut(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('blog_content:home'))


def SignIn(request):

    logged_in = False

    if request.method == "POST" and logged_in == False:

        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username,password=password)

        if user:

            if user.is_active:
                login(request,user)
                logged_in = True
                return HttpResponseRedirect(reverse_lazy('blog_content:home'))

            else:

                return HttpResponse("Account not Active!")

        else:

            print("Failed Login Attempt")
            print("Username: {} and password: {}".format(username, password))
            return render(request, 'Users/signin.html',{"message":"Either User does not exist or credentials are incorrect!"})

    else:
        return render(request, 'Users/signin.html')





def update_user(request):

    if request.method=="POST":

        update_form = User_Update_Form(request.POST,instance=request.user)

        if update_form.is_valid():
            update_form.save()
            return redirect('Users/update_user.html')


    else:

        update_form = User_Update_Form(instance = request.user)
        return render(request,'Users/update_user.html',{'form':update_form})







def change_password(request):
    if request.method=="POST":
        form = PasswordChangeForm(data=request.POST,user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('blog_content:home')


    else:
        form = PasswordChangeForm(data=request.POST,user=request.user)

        args = {'form':form}
        return render(request,'Users/update_password.html',args)

Users/templates/Users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
      <meta charset="UTF-8">
      <title>{% block Title_Block %}{% endblock %}</title>
      <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
      <!--<script src="{% static 'js/jQuery_3.3.1.js' %}"></script>-->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/master.css' %}">


  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'blog_content:list_news' %}">Tech Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tutorials <span class="caret"></span></a>
              <ul class="dropdown-menu  ">
                <li><a href="{% url 'blog_content:list_linux' %}">Linux</a></li>
                <li><a href="{% url 'blog_content:list_bash' %}">Bash</a></li>
                <li><a href="{% url 'blog_content:list_python' %}">Python</a></li>
                <li><a href="{% url 'blog_content:list_perl' %}">Perl</a></li>
              </ul>
            </li>

            <li><a href="{% url 'blog_content:home' %}">About Us</a></li>
          </ul>

          <form class="navbar-form navbar-left" action="{% url 'blog_content:search' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <input id="search_criteria" name="search_criteria" type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default" id="search">Search</button>
          </form>


             <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
                 <li><a href="{% url 'Users:SignIn' %}">Sign In</a></li>
                 <li><a href="{% url 'Users:SignUp' %}">Sign Up</a></li>
            {% else %}

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.username}} <span class="caret"></span></a>
              <ul class="dropdown-menu inverse-dropdown">
                <li><a href="{% url 'Users:update_user'%}">Modify Account</a></li>
                  <li><a href="{% url 'Users:update_password'%}">Change Password</a></li>
                  <li><a href="{% url 'blog_content:add_tutorial' %}">Create Tutorial</a></li>
                  <li><a href="{% url 'blog_content:add_article' %}">Create News Article</a></li>
                  <li><a href="{% url 'blog_content:list_my_articles' %}">Modify My Articles</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'Users:SignOut' %}">Logout</a></li>
              </ul>
            </li>
            {% endif %}
             </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


  {% block Body_Block %}
  {% endblock %}






  </body>
</html>

Users/templates/Users/signin.html
{% extends 'Users/base.html' %}


{% block Title_Block %}Sign In{% endblock %}

{% block Body_Block %}
<div class="col-md-4 col-md-offset-4 jumbotron" style="text-align:center">

    {% if message %}
    <h4>{{message}}</h4>
    {% endif %}
    {% if user.is_authenticated %}
        <h1>You are Signed In!</h1>
    {% else %}
            <h1> Login </h1><br><br>
          <form method="post">
            {% csrf_token %}
             <label for="username">Username: </label>
              <input type="text" name="username" placeholder="Please Enter Username here"><br><br>
              <label for="password">Password: </label>
              <input type="password" name="password" placeholder="Please Enter Password here"><br><br>
            <input type="submit" value="Login" class="btn btn-default">
          </form>

    {% endif %}
</div>
{% endblock %}

Users/templates/Users/signup.html
{% extends 'Users/base.html' %}


{% block Title_Block %}Sign Up{% endblock %}

{% block Body_Block %}
<div class="col-md-6 col-md-offset-3 jumbotron" style="text-align:left">
    <h1>User Signup:</h1><br><br>
    <form method="post">

        {% csrf_token %}
        {% for field in form %}
                            <p>
                                <div>{{ field.label_tag }}</div>
                                <div>{{ field }}</div><br>
                                {% if field.help_text %}
                                    <div ><small>{{ field.help_text|safe }}</small></div>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
        {% endfor %}
        <div style="text-align:center"><input type="submit" value="Sign Up" class="btn btn-default"></div>

    </form>
</div>
{% endblock %}

Users/templates/Users/update_password.html
{% extends 'blog_content/base.html' %}
{% load static %}

{% block Title_Block %}Update Password:{% endblock %}
{% load static %}
{% block Body_Block %}
<div class="col-md-8 col-md-offset-2 jumbotron" style="text-align:left">
    {% if saved %}

    <h3>Data Saved!</h3>

    {% else %}
            <form method="post">
                {% csrf_token %}
            <h1>Update Password for:</h1>
                <h2> {{user.username}}</h2>
            {% for field in form %}
                                    <p>
                                        <div>{{ field.label_tag }}</div>
                                        <div>{{ field }}</div><br>
                                        {% if field.help_text %}
                                            <div ><small>{{ field.help_text|safe }}</small></div>
                                        {% endif %}
                                        {% for error in field.errors %}
                                            <p style="color: red">{{ error }}</p>
                                        {% endfor %}
                                    </p>
             {% endfor %}
            <input type="submit" class="btn btn-default" name="submit" value="Modify"/>
                </form>
        </div>
    {% endif %}
{% endblock %}

Users/templates/Users/update_user.html
{% extends 'blog_content/base.html' %}
{% load static %}

{% block Title_Block %}Update Account:{% endblock %}
{% load static %}
{% block Body_Block %}
<div class="col-md-8 col-md-offset-2 jumbotron" style="text-align:left">
    {% if saved %}

    <h3>Data Saved!</h3>

    {% else %}
            <form method="post">
                {% csrf_token %}
            <h1>Update Account for:</h1>
                <h2> {{user.username}}</h2>
            {% for field in form %}
                                    <p>
                                        <div>{{ field.label_tag }}</div>
                                        <div>{{ field }}</div><br>
                                        {% if field.help_text %}
                                            <div ><small>{{ field.help_text|safe }}</small></div>
                                        {% endif %}
                                        {% for error in field.errors %}
                                            <p style="color: red">{{ error }}</p>
                                        {% endfor %}
                                    </p>
             {% endfor %}
            <input type="submit" class="btn btn-default" name="submit" value="Modify"/>
                </form>
        </div>
    {% endif %}
{% endblock %}